title: "Understanding Spatial Data: Map Projections"
remote_theme: ubc-library-rc/rc-workshop-template
footer_content: "<a href=\"https://github.com/fiddleheads/map-projections/\">View in GitHub</a>"
